### ISSUE TITLE
Metamask Snap - @learncard/types dependency issue

### ISSUE THREAD

**Issue by rishabhansali** [learningeconomy/LearnCard#222]
Hello,

I am trying to work with [metamask snap](https://github.com/learningeconomy/LearnCard/tree/main/services/meta-mask-snap) service using the [example](https://github.com/learningeconomy/LearnCard/tree/main/examples/snap-example-dapp) provided. While starting the service, it returns with the following error:

```
./src/snap.ts → ./dist/snap.js...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
../../../../node_modules/.pnpm/isomorphic-webcrypto@2.3.8_react-native@0.71.3/node_modules/isomorphic-webcrypto/src/webcrypto-shim.mjs
16:         factory(global);
17:     }
18: }(typeof self !== 'undefined' ? self : this, function (global) {
                                           ^
19:     'use strict';
../../../../node_modules/.pnpm/@ethersproject+contracts@5.7.0/node_modules/@ethersproject/contracts/lib.esm/index.js
1: "use strict";
2: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                    ^
3:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
4:     return new (P || (P = Promise))(function (resolve, reject) {
...and 1 other occurrence
../../../../node_modules/.pnpm/@ethersproject+wallet@5.7.0/node_modules/@ethersproject/wallet/lib.esm/index.js
1: "use strict";
2: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                    ^
3:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
4:     return new (P || (P = Promise))(function (resolve, reject) {
...and 1 other occurrence

...and 14 other files
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@learncard/types (imported by src/types/rpc.ts)
created ./dist/snap.js in 8.6s

./src/index.ts → dist/cjs/index.js, dist/esm/index.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@learncard/types (imported by src/types/rpc.ts)
created dist/cjs/index.js, dist/esm/index.js in 220ms

./src/index.ts → dist/index.d.ts...
src/types/rpc.ts(10,8): error TS2307: Cannot find module '@learncard/types' or its corresponding type declarations.

[!] (plugin dts) Error: Failed to compile. Check the logs above.
src/types/rpc.ts
Error: Failed to compile. Check the logs above.
    at error (/Users/rsb/Documents/LearnCard/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:198:30)
    at throwPluginError (/Users/rsb/Documents/LearnCard/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:21718:12)
    at Object.error (/Users/rsb/Documents/LearnCard/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:22672:20)
    at Object.error (/Users/rsb/Documents/LearnCard/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:21895:42)
    at Object.transform (/Users/rsb/Documents/LearnCard/node_modules/.pnpm/rollup-plugin-dts@4.2.3_zptcx3kz3uwp66hzhyyt545weq/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1644:26)
    at /Users/rsb/Documents/LearnCard/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:22879:40

```

I would appreciate if anyone can help me resolve this issue. 

Thank you

**Comment by Custard7** [comment]
Closing this as stale.
